Same workflow step executed twice K8S cluster creation fails
Bug Number: 1976965

This change was made to add logging to log the client IP for every REST
request coming to the POST node. In case of the follower the IP will be
logged as a part of the forwarding log. We added a new log for the
leader to log the client IP.

Also made changes in deployment script to pull the latest version of
c-rest-engine

Tests done:

1) Set up three node POST cluster
2) Target the leader node with any REST request
3) Target leader node with REST request

Oct 25 00:21:12 post-us-east-2a-i-05fa51b87c3e387d6 postd[3038]:
t@139810379200256: VmDirRESTForwardRequest Failed with error: 9806 curl
error: 7, time taken 29 for client: 67.148.5.81 to leader:
post-us-east-2a-i-0853d47ede33b702d.lightwave.local

Oct 24 23:56:10 post-us-east-2a-i-0781fc0642a9b6253 postd[24965]:
t@140478783551232: Leader received REST request from: 172.32.65.133

Oct 25 00:20:59 post-us-east-2a-i-05fa51b87c3e387d6 postd[3038]:
t@139810286880512: Proxy forwarding done for client: 67.148.5.81 to
leader: post-us-east-2a-i-0853d47ede33b702d.lightwave.local time taken:
15 milliseconds

Oct 25 18:03:46 post-us-east-2a-i-0781fc0642a9b6253 postd[1913]:
t@140203880597248: Leader received REST request from: 172.32.65.133
request type: GET request URI: /v1/post/ldap

Change-Id: I147e3d4c362687e42b45892a39a8f9f8cfb51c59