PR 1942403: ignore legacy schema blob patch and ignore tombstone schema blob
1. bypass legacy schema blob patch

2. add allow deletion of SUB_SCEHMA_SUB_ENTRY_ID in legach_check

3. in server startup, if SUB_SCEHMA_SUB_ENTRY_ID entry is no longer
   "cn=aggregate,cn=schemacontext", treat it as if entry not found.
   so if we clean up legacy blob entry, vmdir continue to start while it is in tombstone.

3.1 clean up legacy entry
3.2 ldapdelete xxx "cn=aggregate,cn=schemacontext"
3.3 in vmdir log file, you should see some thing like:
ERROR: DecodeEntry failed (9602) DN:(cn=aggregate#objectGUID:187ac1c1-924d-4b16-a40d-fcea4ab35e7b,cn=Deleted Objects,dc=vsphere,dc=local)
3.4 ldapdelete xxx "cn=aggregate#objectGUID:187ac1c1-924d-4b16-a40d-fcea4ab35e7b,cn=Deleted Objects,dc=vsphere,dc=local"

4. remove vmdir -u (schema patch) from vmdir_upgrade.sh script.

Change-Id: Id9719e0060b96be3869e61eec0541323af53d941